### ISSUE TITLE
CarLeaseApp v2.0 roadmap

### ISSUE THREAD

**Issue by amir5000** [amir5000/CarLeaseApp#2]
Here are the required tasks to finish for taking app to v2.0*:

- [ ] Architect app using ReactJs, Redux, ES6, create-react-app, Bootstrap 4 Sass, and decide on either FireBase or GraphQL for server database. 
- [ ] Enable Users to create a leased car profile
- [ ] Once profile is created then populate dashboard with all relevant data and calculations.

* This will be a complete re-write of the app from the ground up.
